sbatch jeanzay_sbatch_cv.sh train_kd.py hparams/train_kd_sgd_fr.yaml "--data_folder $SCRATCH/cv-corpus-6.1-2020-12-11/fr/ --pretrain_st_dir /gpfswork/rech/kxg/uyk21ll/workspace/speechbrain/speechbrain-released/tea_models/st --tea_infer_dir /gpfsscratch/rech/zfg/uyk21ll/tea_save/ --output_folder results/best_015drop_1lr"
sbatch jeanzay_sbatch_cv.sh train_kd.py hparams/train_kd_sgd_fr.yaml "--data_folder $SCRATCH/cv-corpus-6.1-2020-12-11/fr/ --pretrain_st_dir /gpfswork/rech/kxg/uyk21ll/workspace/speechbrain/speechbrain-released/tea_models/st --tea_infer_dir /gpfsscratch/rech/zfg/uyk21ll/tea_save/ --output_folder results/weighted_015drop_1lr --strategy weighted"
sbatch jeanzay_sbatch_cv.sh train_kd.py hparams/train_kd_sgd_fr.yaml "--data_folder $SCRATCH/cv-corpus-6.1-2020-12-11/fr/ --pretrain_st_dir /gpfswork/rech/kxg/uyk21ll/workspace/speechbrain/speechbrain-released/tea_models/st --tea_infer_dir /gpfsscratch/rech/zfg/uyk21ll/tea_save/ --output_folder /home/yan/kd_commonvoice_fr/results/topk_015drop_1lr --strategy top-k"

sbatch jeanzay_sbatch_cv.sh train_kd.py hparams/train_kd_sgd_fr.yaml "--data_folder $SCRATCH/cv-corpus-6.1-2020-12-11/fr/ --pretrain_st_dir /gpfswork/rech/kxg/uyk21ll/workspace/speechbrain/speechbrain-released/tea_models/st --tea_infer_dir /gpfsscratch/rech/zfg/uyk21ll/tea_save/ --output_folder results/best_ceonly_015drop_1lr --ceonly True"
sbatch jeanzay_sbatch_cv.sh train_kd.py hparams/train_kd_sgd_fr.yaml "--data_folder $SCRATCH/cv-corpus-6.1-2020-12-11/fr/ --pretrain_st_dir /gpfswork/rech/kxg/uyk21ll/workspace/speechbrain/speechbrain-released/tea_models/st --tea_infer_dir /gpfsscratch/rech/zfg/uyk21ll/tea_save/ --output_folder results/weighted_ceonly_015drop_1lr --ceonly True --strategy weighted"
sbatch jeanzay_sbatch_cv.sh train_kd.py hparams/train_kd_sgd_fr.yaml "--data_folder $SCRATCH/cv-corpus-6.1-2020-12-11/fr/ --pretrain_st_dir /gpfswork/rech/kxg/uyk21ll/workspace/speechbrain/speechbrain-released/tea_models/st --tea_infer_dir /gpfsscratch/rech/zfg/uyk21ll/tea_save/ --output_folder results/topk_ceonly_015drop_1lr --ceonly True --strategy top-k"

sbatch jeanzay_sbatch_cv.sh train_kd.py hparams/train_kd_sgd_fr.yaml "--data_folder $SCRATCH/cv-corpus-6.1-2020-12-11/fr/ --pretrain_st_dir /gpfswork/rech/kxg/uyk21ll/workspace/speechbrain/speechbrain-released/tea_models/st --tea_infer_dir /gpfsscratch/rech/zfg/uyk21ll/tea_save/ --output_folder results/average_015drop_1lr --strategy average"
