python train_kd.py hparams/train_kd_sgd_fr.yaml --data_folder /datasets/commonvoice/fr/cv-corpus-6.1-2020-12-11/fr --pretrain_st_dir /home/yan/kd_commonvoice_fr/tea_models/st --tea_infer_dir /hdd1/yan/kd_results_fr/teachers_save/ --output_folder /home/yan/kd_commonvoice_fr/results/best_015drop_1lr
python train_kd.py hparams/train_kd_sgd_fr.yaml --data_folder /datasets/commonvoice/fr/cv-corpus-6.1-2020-12-11/fr --pretrain_st_dir /home/yan/kd_commonvoice_fr/tea_models/st --tea_infer_dir /hdd1/yan/kd_results_fr/teachers_save/ --output_folder /home/yan/kd_commonvoice_fr/results/weighted_015drop_1lr --strategy weighted
python train_kd.py hparams/train_kd_sgd_fr.yaml --data_folder /datasets/commonvoice/fr/cv-corpus-6.1-2020-12-11/fr --pretrain_st_dir /home/yan/kd_commonvoice_fr/tea_models/st --tea_infer_dir /hdd1/yan/kd_results_fr/teachers_save/ --output_folder /home/yan/kd_commonvoice_fr/results/topk_015drop_1lr --strategy top-k

python train_kd.py hparams/train_kd_sgd_fr.yaml --data_folder /datasets/commonvoice/fr/cv-corpus-6.1-2020-12-11/fr --pretrain_st_dir /home/yan/kd_commonvoice_fr/tea_models/st --tea_infer_dir /hdd1/yan/kd_results_fr/teachers_save/ --output_folder /home/yan/kd_commonvoice_fr/results/best_ceonly_015drop_1lr --ceonly True
python train_kd.py hparams/train_kd_sgd_fr.yaml --data_folder /datasets/commonvoice/fr/cv-corpus-6.1-2020-12-11/fr --pretrain_st_dir /home/yan/kd_commonvoice_fr/tea_models/st --tea_infer_dir /hdd1/yan/kd_results_fr/teachers_save/ --output_folder /home/yan/kd_commonvoice_fr/results/weighted_ceonly_015drop_1lr --ceonly True --strategy weighted
python train_kd.py hparams/train_kd_sgd_fr.yaml --data_folder /datasets/commonvoice/fr/cv-corpus-6.1-2020-12-11/fr --pretrain_st_dir /home/yan/kd_commonvoice_fr/tea_models/st --tea_infer_dir /hdd1/yan/kd_results_fr/teachers_save/ --output_folder /home/yan/kd_commonvoice_fr/results/topk_ceonly_015drop_1lr --ceonly True --strategy top-k

python train_kd.py hparams/train_kd_sgd_fr.yaml --data_folder /datasets/commonvoice/fr/cv-corpus-6.1-2020-12-11/fr --pretrain_st_dir /home/yan/kd_commonvoice_fr/tea_models/st --tea_infer_dir /hdd1/yan/kd_results_fr/teachers_save/ --output_folder /home/yan/kd_commonvoice_fr/results/average_015drop_1lr --strategy average
